#!/bin/bash

echo "Executing scope action=$SERVICE_ACTION, type=$SERVICE_ACTION_TYPE for scope=$SCOPE_ID"

map_custom_action() {
  local action="$1"
  
  case "$action" in
    "delete-scope")
      echo "delete"
      ;;
    "diagnose-scope")
      echo "diagnose"
      ;;
    *)
      echo "$action"
      ;;
  esac
}


ACTION_TO_EXECUTE=""

case "$SERVICE_ACTION_TYPE" in
  "custom")
      ACTION_TO_EXECUTE=$(map_custom_action "$SERVICE_ACTION")
    ;;
  *)
    ACTION_TO_EXECUTE="$SERVICE_ACTION_TYPE"
    ;;
esac

WORKFLOW_PATH="$SERVICE_PATH/scope/workflows/$ACTION_TO_EXECUTE.yaml"

if [[ ! -f "$WORKFLOW_PATH" ]]; then
  IFS=',' read -ra OVERRIDE_PATHS <<< "$OVERRIDES_PATH"
  for path in "${OVERRIDE_PATHS[@]}"; do
    path=$(echo "$path" | xargs)
    WORKFLOW_PATH="$path/scope/workflows/$ACTION_TO_EXECUTE.yaml"
    if [[ -f "$WORKFLOW_PATH" ]]; then
      break;
    fi
  done
else
  OVERRIDES_WORKFLOW_PATH="$OVERRIDES_PATH/scope/workflows/$ACTION_TO_EXECUTE.yaml"
fi

CMD="np service workflow exec --workflow $WORKFLOW_PATH --build-context --include-secrets"

IFS=',' read -ra OVERRIDE_PATHS <<< "$OVERRIDES_PATH"
for path in "${OVERRIDE_PATHS[@]}"; do
  # Trim whitespace
  path=$(echo "$path" | xargs)
  OVERRIDE_WORKFLOW_PATH="$path/scope/workflows/$ACTION_TO_EXECUTE.yaml"
  if [[ -f "$OVERRIDE_WORKFLOW_PATH" ]]; then
    CMD="$CMD --overrides $OVERRIDE_WORKFLOW_PATH"
  fi
done

echo "Executing command: $CMD"
eval $CMD

