#!/bin/bash

set -eou pipefail

TOFU_VAR_FILE="$TOFU_MODULE_DIR/.tfvars.json"
echo "$TOFU_VARIABLES" > "$TOFU_VAR_FILE"

CURRENT_DIR=$(dirname "${BASH_SOURCE[0]}")

cd "$CURRENT_DIR"

tofu -chdir="$TOFU_MODULE_DIR" init -input=false $TOFU_INIT_VARIABLES
tofu -chdir="$TOFU_MODULE_DIR" "$TOFU_ACTION" -auto-approve -var-file="$TOFU_VAR_FILE"
