#!/bin/bash

ACTION_TO_EXECUTE="metric"


if [[ "$NOTIFICATION_ACTION" == "metric:list" ]]; then
  ACTION_TO_EXECUTE="list"
fi

WORKFLOW_PATH="$SERVICE_PATH/metric/workflows/$ACTION_TO_EXECUTE.yaml"

CMD="np service workflow exec --no-output --workflow $WORKFLOW_PATH"

IFS=',' read -ra OVERRIDE_PATHS <<< "$OVERRIDES_PATH"
for path in "${OVERRIDE_PATHS[@]}"; do
  # Trim whitespace
  path=$(echo "$path" | xargs)
  OVERRIDE_WORKFLOW_PATH="$path/metric/workflows/$ACTION_TO_EXECUTE.yaml"
  if [[ -f "$OVERRIDE_WORKFLOW_PATH" ]]; then
    CMD="$CMD --overrides $OVERRIDE_WORKFLOW_PATH"
  fi
done

eval $CMD