#!/bin/bash

echo "Executing deployment action=$SERVICE_ACTION for scope=$SCOPE_ID and deployment=$DEPLOYMENT_ID"

ACTION_TO_EXECUTE=""

case "$SERVICE_ACTION" in
  "start-initial")
    ACTION_TO_EXECUTE="initial"
    ;;
  "start-blue-green")
  ACTION_TO_EXECUTE="blue_green"
    ;;
  "switch-traffic")
    ACTION_TO_EXECUTE="switch_traffic"
    ;;
  "rollback-deployment")
    ACTION_TO_EXECUTE="rollback"
    ;;
  "finalize-blue-green")
    ACTION_TO_EXECUTE="finalize"
    ;;
  "delete-deployment")
    ACTION_TO_EXECUTE="delete"
    ;;
  "diagnose-deployment")
    ACTION_TO_EXECUTE="diagnose"
    ;;
  "kill-instances")
    ACTION_TO_EXECUTE="kill_instances"
    ;;
  *)
    echo "Unknown action: $SERVICE_ACTION"
    exit 1
    ;;
esac

WORKFLOW_PATH="$SERVICE_PATH/deployment/workflows/$ACTION_TO_EXECUTE.yaml"

CMD="np service workflow exec --workflow $WORKFLOW_PATH --build-context --include-secrets"

IFS=',' read -ra OVERRIDE_PATHS <<< "$OVERRIDES_PATH"
for path in "${OVERRIDE_PATHS[@]}"; do
  # Trim whitespace
  path=$(echo "$path" | xargs)
  OVERRIDE_WORKFLOW_PATH="$path/deployment/workflows/$ACTION_TO_EXECUTE.yaml"
  if [[ -f "$OVERRIDE_WORKFLOW_PATH" ]]; then
    CMD="$CMD --overrides $OVERRIDE_WORKFLOW_PATH"
  fi
done

echo "Executing command: $CMD"
eval $CMD
